In [1]:
import numpy as np

In [3]:
"""Question 1"""

arr = np.random.randint(1 , 100 , size=(3 , 3))
print(arr)

arr1 = arr.T
print(arr1)

[[ 9 77 15]
 [87 86 68]
 [94 42 58]]
[[ 9 87 94]
 [77 86 42]
 [15 68 58]]


In [2]:
"""Question 2"""

arr2 = np.random.randint(1 , 10 , 10)
print(arr2)

print("\n")


arr3 = arr2.reshape(5 , 2)
print(arr3)

print("\n")

arr4 = arr3.reshape(2 , 5)
print(arr4)

[3 2 7 4 8 4 5 4 5 5]


[[3 2]
 [7 4]
 [8 4]
 [5 4]
 [5 5]]


[[3 2 7 4 8]
 [4 5 4 5 5]]


In [11]:
"""Question 3"""

arr = np.random.rand(4 , 4)
print(arr)
print("\n")
arr1 = np.pad(arr , 2 , mode='constant')
print(arr1)


[[0.36116416 0.22401711 0.35182995 0.27563214]
 [0.75740138 0.10371422 0.40829534 0.90894159]
 [0.51115668 0.45964856 0.48196115 0.5707185 ]
 [0.34155465 0.86786417 0.97081388 0.44976557]]


[[0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.36116416 0.22401711 0.35182995 0.27563214
  0.         0.        ]
 [0.         0.         0.75740138 0.10371422 0.40829534 0.90894159
  0.         0.        ]
 [0.         0.         0.51115668 0.45964856 0.48196115 0.5707185
  0.         0.        ]
 [0.         0.         0.34155465 0.86786417 0.97081388 0.44976557
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.        ]]


In [17]:
"""Question 4"""
arr5 = np.arange(10 , 61 , 5 , dtype=int)
arr5

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

In [21]:
"""Question 5"""
a = np.array(['python' , 'numpy' , 'pandas'])

allupper = np.char.upper(a)
print(allupper)

alllower = np.char.lower(a)
print(alllower)

capitalize = np.char.capitalize(a)
print(capitalize)


['PYTHON' 'NUMPY' 'PANDAS']
['python' 'numpy' 'pandas']
['Python' 'Numpy' 'Pandas']


In [60]:
"""Question 6"""

words = ["Rupam" , "Avik" , "Apple"]
words_arr=  np.array(words)
def space(word):
    return ' '.join(word)
space = np.array([space(word) for word in words])
print(space)

['R u p a m' 'A v i k' 'A p p l e']


In [26]:
"""Question 7"""

a = np.array([[1 , 2 , 3] , [4 , 5 , 6] , [7 , 8 , 9]])
b = a + 5
print(b)
print("\n")
c = a * 5
print(c)
print("\n")

d = a - 5
print(d)
print("\n")

e = a / 2
print(e)
print("\n")

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


[[-4 -3 -2]
 [-1  0  1]
 [ 2  3  4]]


[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]




In [28]:
"""Question 8"""

arr8 = np.eye(5 , dtype=int)
arr8

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [38]:
"""Question 9"""

l = []
def isprime(n):
    if n <= 1:
        return
    if n == 2 or n == 3:
        l.append(n)
        return
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return
    l.append(n)

g = np.linspace(0, 1000, 100, dtype=int)
for i in range(len(g)):
    isprime(g[i])

print(np.array(l))


[101 131 151 181 191 313 353 373 383 727 757 787 797 919 929]


In [51]:
"""Question 10"""

temp = np.random.randint(10 , 30 , (4 , 7) , dtype=int)
avg_temp = []
t = np.shape(temp)
for i in range(0 , t[0]):
    sum = 0
    for j in range(0 , t[1]):
        sum = sum + temp[i][j]
    avg_temp.append(sum / 7)

ans = np.array(avg_temp)
print(ans)

[20.85714286 18.71428571 18.28571429 18.42857143]
