In [ ]:
#Question 1

"""
Numpy is internally made by c language. As we all know c is
one the fastest language in programming world. Although it is python 
library still it is faster because of c language. That's why numpy 
brings so much numerical operation power to python
"""

In [2]:
#Question  2

import numpy as np

data = [10 , 20 , 30 , 40 , 50]
count = [1 , 2 , 3 , 4 , 5]
print(np.mean(data))
print(np.average(data , weights=count))

"""
When we wanna just calculate the total element sum / lenght of 
array. Then np.mean can be good function. np.average is used to
calculate weighted average of data set. example is given above.
"""

30.0
36.666666666666664


'\nWhen we wanna just calculate the total element sum / lenght of \narray. Then np.mean can be good function. np.average is used to\ncalculate weighted average of data set. example is given above.\n'

In [ ]:
"""Question 5"""

"""
Numpy array is different that normal python list first of all
list is heterogenous data structure in nature but ndarray is homogenous
in nature. array size should be declared that makes it more efficuent
in case of operation but list size is not fixed.Also arrays are optimised
for mathermatical calculation
"""

In [5]:
"""Question 6"""

#vstack() -->
"""vstack helps to stack 2 ndarray vertically"""
arr1 = np.array([[1 , 2] , [3 , 4]])
arr2 = np.array([[5 , 6] , [7 , 8]])

print(np.vstack((arr1 , arr2)))
print("\n")

#hstack() -->
"""hstack helps to stack 2 ndarray horizontally"""
arr1 = np.array([[1 , 2] , [3 , 4]])
arr2 = np.array([[5 , 6] , [7 , 8]])

print(np.hstack((arr1 , arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


In [9]:
"""Question 9"""

#Evenly splict
arr = np.array([1 , 2 , 3 , 4 , 5 , 6])
sp_array = np.array_split(arr , 2)
print(sp_array)

#Uneven splic
arr_un = np.array([1 , 2 , 3 , 4 , 5])
sp_array_un = np.array_split(arr_un , 3)
print(sp_array_un)

"""
for uneven partition it tries to put minimum numbers possible
to the subarray.
"""


[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5])]


In [ ]:
"""Question 10"""

"""Vectorization refers to the process of performing 
operations on entire arrays without explicit loops. It is extremely
faster in terms of optimization"""

"""Broadcasting is a powerful mechanism that allows NumPy to perform 
arithmetic operations on arrays of different shapes"""