In [ ]:
#Question 1

"""
Numpy is internally made by c language. As we all know c is
one the fastest language in programming world. Although it is python 
library still it is faster because of c language. That's why numpy 
brings so much numerical operation power to python
"""

In [2]:
#Question  2

import numpy as np

data = [10 , 20 , 30 , 40 , 50]
count = [1 , 2 , 3 , 4 , 5]
print(np.mean(data))
print(np.average(data , weights=count))

"""
When we wanna just calculate the total element sum / lenght of 
array. Then np.mean can be good function. np.average is used to
calculate weighted average of data set. example is given above.
"""

30.0
36.666666666666664


'\nWhen we wanna just calculate the total element sum / lenght of \narray. Then np.mean can be good function. np.average is used to\ncalculate weighted average of data set. example is given above.\n'

In [4]:
"""Question 3"""

#Reverse 1d array 

array_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = array_1d[::-1]
print(reversed_1d)

#Reverse 2d array

array_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

reversed_2d = np.flip(array_2d)
print(reversed_2d)


[5 4 3 2 1]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [11]:
"""Question 4"""
array = np.array([1, 2, 3])
print(array.dtype)

"""
array is homogenous in nature and also it is takes contiguous memory
location which makes it more faster. Also it is fixed when the size
of array is declared so memory usage is obiously optimes here
"""

int64


In [ ]:
"""Question 5"""

"""
Numpy array is different that normal python list first of all
list is heterogenous data structure in nature but ndarray is homogenous
in nature. array size should be declared that makes it more efficuent
in case of operation but list size is not fixed.Also arrays are optimised
for mathermatical calculation
"""

In [ ]:
"""Question 6"""

"""
Numpy array is more optimized because as we know arrays contains
fixed type of data. It only stores same type of data type so it increases
the memory efficiency. Arrays are also contiguous in nature as it
is stored as block of memory so it is easy to access so fast
"""

In [5]:
"""Question 7"""

#vstack() -->
"""vstack helps to stack 2 ndarray vertically"""
arr1 = np.array([[1 , 2] , [3 , 4]])
arr2 = np.array([[5 , 6] , [7 , 8]])

print(np.vstack((arr1 , arr2)))
print("\n")

#hstack() -->
"""hstack helps to stack 2 ndarray horizontally"""
arr1 = np.array([[1 , 2] , [3 , 4]])
arr2 = np.array([[5 , 6] , [7 , 8]])

print(np.hstack((arr1 , arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


In [10]:
"""Question 8"""
#numpy.fliplr()

"""Flips the array in the left or right direction"""
array_2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

flipped_lr = np.fliplr(array_2d)
print(flipped_lr)

#numpy.flipud()

""" Flips the array in the up or down direction"""

flipped_ud = np.flipud(array_2d)
print(flipped_ud)


[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


In [9]:
"""Question 9"""

#Evenly splict
arr = np.array([1 , 2 , 3 , 4 , 5 , 6])
sp_array = np.array_split(arr , 2)
print(sp_array)

#Uneven splic
arr_un = np.array([1 , 2 , 3 , 4 , 5])
sp_array_un = np.array_split(arr_un , 3)
print(sp_array_un)

"""
for uneven partition it tries to put minimum numbers possible
to the subarray.
"""


[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5])]


In [ ]:
"""Question 10"""

"""Vectorization refers to the process of performing 
operations on entire arrays without explicit loops. It is extremely
faster in terms of optimization"""

"""Broadcasting is a powerful mechanism that allows NumPy to perform 
arithmetic operations on arrays of different shapes"""